name: Build and Deploy leetscrape to Google Cloud Run
 
on:
  # push:
  #  branches: [ main ]
  pull_request:
   branches: [ main ]
 
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: ai-interview-prep-app
  REGION: us-central1
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
 
 
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
 
    - name: Configure Docker to use gcloud
      run: gcloud auth configure-docker
 
    - name: Build Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} -f leetscrape_service/Dockerfile .
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}
 
    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --port 8010 \
          

    - name: Show deployed service URL
      run: echo "Service deployed to ${{ steps.deploy.outputs.url }}"